### PR TITLE
Added hide when in menu/shortcut/unavalible to Floor and mag

### PR DESCRIPTION
**Pull request by Derfliest**

### CODE REVIEW

**Comment by Solybum** [comment]
Something's wrong here.
The files you are committing are in the root of the repo, and there should not be any addon files there.

Can you look into that?

**Comment by Solybum** [comment]
Can you remove the files in the root (they are still present in the PR it seems.

**Comment by Derfliest** [comment]
yes ill see if i can fix it

**Comment by Derfliest** [comment]
It should be fixed now lol

**Comment by Derfliest** [comment]
hey i dont know how to do it cause im new to github but i was only trying to commit the two lua in item reader for you to check out. i dont know how to remove commits. I was messing with the player reader to try to get the HP bar to have the same functionality but was unsuccessful. I will keep trying though

**Comment by Solybum** [comment]
While it is possible to "revert" commits, I'd suggest to think of it as "correcting changes".

In the original case, since you had some files in the root of the repository that belonged to an addon folder, you'd just delete the file in the root, while keeping a copy of the content to paste into the actual addon file.

Also I assume you saw the issue of content being copy pasted like 3 times in the same addon file which obviously is a big issue as that might actually break the addon.

If you'd rather not have all these commits, the best option would be to close the PR without merging, making a new one based on a different branch (out of the commit you started originally) and modifying the files again.

**Comment by Solybum** [comment]
Any chance you can contact me on Discord @ Soly#0637 ?

**Pull request merged**
